### ISSUE TITLE
Parser for scss

### ISSUE THREAD

**Issue by gegoune** [tree-sitter/tree-sitter-css#16]
Hi,
not sure where is the best place to ask about it. Feel free to delete it if that's not the right place.
I extensively work with `scss` and would really like to have tree sitter parser for it. Could support for `sass/scss` be added to this parser or does new one need to be created?

Thanks.

**Comment by timsofteng** [comment]
Same question

**Comment by gegoune** [comment]
It already exists: https://github.com/serenadeai/tree-sitter-scss.

**Comment by timsofteng** [comment]
@gegoune scss style section in `.vue` file still wrong
![image](https://user-images.githubusercontent.com/51912173/123289895-82c85d80-d519-11eb-9f35-3e845034eeab.png)
