### ISSUE TITLE
Add license to repo

### ISSUE THREAD

**Issue by zachwaugh** [tree-sitter/tree-sitter-css#2]
I'm doing some tree-sitter work and wanted to use the languages, but I noticed this one doesn't have a license. All the other ones I've looked at (tree-sitter-html, tree-sitter-css, etc) are MIT licensed. Could you add one here whenever you get a chance?

**Comment by maxbrunsfeld** [comment]
Done! Thanks for pointing that out.

**Comment by zachwaugh** [comment]
Thanks for the quick fix!
