### ISSUE TITLE
"Undefined symbols for architecture x86_64" error when requiring in another parser

### ISSUE THREAD

**Issue by matthew-dean** [tree-sitter/tree-sitter-css#21]
I'm attempting to do this to create a Less parser:
```
const css = require('tree-sitter-css/grammar')
module.exports = grammar(css, { ...
```
This throws the `Undefined symbols` error on `tree-sitter parse` and `tree-sitter test`. Is this a `tree-sitter` issue or an issue with the implementation in this repo? Related: https://github.com/tree-sitter/tree-sitter/issues/1497

**Comment by amaanq** [comment]
you need to copy the scanner over and rename the lang functions to less
