### ISSUE TITLE
Wrong comments highlighting in styled components

### ISSUE THREAD

**Issue by timsofteng** [tree-sitter/tree-sitter-css#31]
In styled components we can comment the code with `//`
So comments should look like this:

![image](https://user-images.githubusercontent.com/51912173/182137033-0af40726-8d36-403d-9c20-feb5e8b0b16a.png)

Instead we get this:
![image](https://user-images.githubusercontent.com/51912173/182137085-539294fe-54d7-422b-9df6-e0c9cbe2a0a9.png)

**Comment by amaanq** [comment]
fixed on master, and I created a release (0.20.0)
