### ISSUE TITLE
Classes and property keys both get `@property` group

### ISSUE THREAD

**Issue by chrisgrieser** [tree-sitter/tree-sitter-css#34]
This is noticeable when comparing the default css highlighting with the one from this TS parser:

default css syntax highlighting
<img width="640" alt="Pasted image 2022-11-17 00 41 15" src="https://user-images.githubusercontent.com/73286100/202318838-deee9855-fa93-42fb-95df-f2f3f0001eb4.png">

TS css parser
<img width="615" alt="Pasted image 2022-11-17 00 42 54" src="https://user-images.githubusercontent.com/73286100/202318888-088b0913-acd8-4f36-9ba3-6a921dab6b0b.png">

the white color is simply a color scheme issue – the parser issue is that both, the classes in the selector and the property, both get the same group `@property`, which I checked with TS playground:
<img width="457" alt="Pasted image 2022-11-17 00 44 41" src="https://user-images.githubusercontent.com/73286100/202319096-8d38ba93-fd05-412b-a2af-c88b5ce35cc4.png">
<img width="426" alt="Pasted image 2022-11-17 00 45 10" src="https://user-images.githubusercontent.com/73286100/202319137-d5c0456e-91ea-4d16-a59f-731f2dedd509.png">

Overall, this leads to worse syntax highlighting, regardless the theme.

**Comment by sammce** [comment]
Just writing to +1 this. I'm pulling my hair out trying to get it to look nice in `.svelte` files with the Dracula theme. If I could figure out how to use the default syntax highlighting for css in the `<style>` tag I 100% would.

**Comment by samhed** [comment]
Same, for this reason, I disable highlights for CSS. Is there any way I can help to get this resolved?

**Comment by Astanusic** [comment]
Got the same issue for so long now, if there is any way I can help to fix this I'm up.

**Comment by Astanusic** [comment]
Got it working by introducing new queries in the `highlights.scm` file and by affecting them a hl group.
I need to find where queries and highlights group are being matched so I will able to fix it.

**Comment by samhed** [comment]
Sounds great @Astanusic! I'm happy to test your changes once you have a patch available.

**Comment by samhed** [comment]
@Astanusic do you have a fix you could share? Is there anything I can do to help?

**Comment by chrisgrieser** [comment]
@amaanq Sorry to bother you, but may I ask what the reason is for this issue being closed as "not planned"? 

css is the only language I use where I am disabling treesitter highlighting because the colors are worse with it, and there seem to be several people who with agree.

**Comment by lucario387** [comment]
As this seems neovim-specific, let's cook up a version inside neovim first, shall we?
Yes, nvim-treesitter is closely following (almost carbon copy of) tree-sitter-css highlight queries for captures. That doesn't mean it can't change. If you want the highlights to change, be the change you want to have :smile:. 
The queries were created 3 years ago, so not only the "default" captures have changed, so is the perception of what is better or not. So let's change the capture and pitch a PR for that.

**Comment by chrisgrieser** [comment]
Looks like the issue got fixed: https://github.com/nvim-treesitter/nvim-treesitter/commit/505a0e74cb82dfd1938dcc0eb2526c24abc345e2
🥳

**Comment by chrisgrieser** [comment]
@samhed It looks fine on my end. Didn't do anything other than upgrading nvim-treesitter and then updating the parser.
![Pasted image 2024-01-24 at 16 34 53@2x](https://github.com/tree-sitter/tree-sitter-css/assets/73286100/8cd3eb56-5125-4188-8bd4-e5f7e04763d9)

Have you updated the parsers via `:TSUpdate` after the nvim-treesitter-update? Maybe reinstalling the css parser could fix the issue, if there is something stuck? Otherwise, I guess you'll have to report a bug at nivm-treesitter.

**Comment by amaanq** [comment]
sorry for not responding before @chrisgrieser I forgot about this but yea this was an issue in nvim-treesitter (not here) that got resolved

Locking since it's unrelated, any other issues like this should be reported to nvim-treesitter, this is for the *parser*
