### ISSUE TITLE
Windows detected possible trojan for css.so

### ISSUE THREAD

**Issue by monologuemind** [tree-sitter/tree-sitter-css#35]
This may be the incorrect place to post this so I might cross post on the nvim-treesitter repository as well. I was messing around with neovim but received an notification from windows defender about a possible trojan (Trojan:Win64/Cobaltstrike.RDA!MTB). The file specifically was located here: "nvim-treesitter\parser\css.so".

I can only assume that this file was created after I installed css language support with nvim-treesitter.

I uploaded it to virus total (https://www.virustotal.com/gui/file/6898b45039bfd4bcb56fa9a82a359d07b8fcd688ba68ce06913c224d04c60aea/behavior) and while it didn't suggest that it was malicious it did mention some odd behavior. 

I'm hoping this is a false positive but you never know. My apologies if this is something more specific to my setup.

**Comment by amaanq** [comment]
Just windows things...
