### ISSUE TITLE
Media features scoped as keyword_query

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-css#5]
```css
@media screen and (color) and (color: 8) {}
```

The first `color` is `keyword_query` whereas the second is `feature_name`. Both should be `feature_name`.

[W3C documentation](https://www.w3.org/TR/2017/CR-mediaqueries-4-20170905/#mq-boolean-context).

**Comment by amaanq** [comment]
Like I mentioned in the other issue, we can't determine this dynamically - use queries to fine-tune this
