### ISSUE TITLE
bug: Identifier considers non-ASCII an error

### ISSUE THREAD

**Issue by anarchodin** [tree-sitter/tree-sitter-css#50]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-css

### Describe the bug

In an editor, I noticed that a class selector gets marked as an error if I use non-ASCII letters. Looking at the source code here, it seems that identifiers are constrained to ASCII. This is not correct; CSS allows basically any non-ASCII character in identifiers.

### Steps To Reproduce/Bad Parse Tree

Use a non-ASCII character in an identifier. One example is the letter á.

### Expected Behavior/Parse Tree

Non-ASCII letters should not appear as errors.

### Repro

```CSS
/* Example code that fails to parse */
.skráning {
  background-color: white;
}
```

**Comment by amaanq** [comment]
thanks for the bug report, this is now fixed
