### ISSUE TITLE
bug: `{` breaks string_values 

### ISSUE THREAD

**Issue by tjdevries** [tree-sitter/tree-sitter-css#51]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-css

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6

### Describe the bug

If you start with something like this (similar to the test in the corpuse):

```
============================
Strings
============================

a {
  b: '';
  c: '\'hi\'';
  d: 'hello}';
}

---

(stylesheet
  (rule_set
    (selectors
      (tag_name))
    (block
      (declaration
        (property_name)
        (string_value))
      (declaration
        (property_name)
        (string_value))
      (declaration
        (property_name)
        (string_value)))))
```

But then change the string to now include a `{` token, it errors like:
```
============================
Strings
============================

a {
  b: '';
  c: '\'hi\'';
  d: '{hello}';
}
```

![image](https://github.com/user-attachments/assets/b0c8d142-973f-47c9-9a2d-1890e7ebbb14)

I'm not sure if this is a CSS feature or if it's a bug in the parser (it seems to be a bug in the parser though)

### Steps To Reproduce/Bad Parse Tree

Described above

### Expected Behavior/Parse Tree

It should just return a string_value without error

### Repro

```CSS
.foo {
  color: '{hello}';
}
```

**Comment by amaanq** [comment]
thanks for the bug report TJ :slightly_smiling_face:, this is now fixed

**Comment by tjdevries** [comment]
Great!! Thanks :)
